// beliefs-enum.mjs
//
// Single source of truth for valid belief slugs and the belief slug namespace.
//
// Belief slugs are emitted by the classifier inside `themes_likely[]` using
// the namespaced form `belief.<slug>` to avoid collision with theme slugs of
// the same name (e.g. `agent-first` exists in both spaces).
//
// Resolution flow:
//   classifier emits `themes_likely: ['belief.agent-first', 'voice-ai-craft']`
//   → groqHandler partitions by `isBeliefSlug(slug)` → calls getBeliefExtract
//     for beliefs, getThemeExtract for themes
//   → card-meta resolves `belief.<slug>` → /wiki/beliefs/<slug>/ URL
//
// Loaded from wiki-extracts.json belief data (which is generated by
// scripts/build-wiki-extracts.mjs walking wiki/beliefs/<slug>/index.html).
//
// Per docs/plans/fluffy-tinkering-crane.md F3 (autoplan eng E1+E5 fix —
// prefix string lives in ONE place, imported everywhere).
// Per docs/plans/enter-v3.1-spec.md §5 Phase 3 + §6 Decision 3.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __thisDir = dirname(fileURLToPath(import.meta.url));

// Namespace prefix. Every belief slug emitted across the wire is `belief.<slug>`.
// NEVER hardcode this string anywhere else — import BELIEF_NAMESPACE from here.
export const BELIEF_NAMESPACE = 'belief.';

// Load belief slugs from wiki-extracts.json. Same loader pattern as
// wiki-retrieval.mjs (try several candidate paths to handle netlify's
// esbuild bundling layout).
function loadBeliefs() {
  const candidates = [
    resolve(__thisDir, 'wiki-extracts.json'),
    resolve(__thisDir, 'lib', 'wiki-extracts.json'),
    resolve(__thisDir, '..', 'lib', 'wiki-extracts.json'),
    resolve(__thisDir, '..', 'wiki-extracts.json'),
  ];
  for (const path of candidates) {
    try {
      const text = readFileSync(path, 'utf8');
      const data = JSON.parse(text);
      return data?.beliefs || {};
    } catch {
      // try next
    }
  }
  return {};
}

const _beliefsData = loadBeliefs();

// Bare belief slugs (without `belief.` prefix). Sorted alphabetically.
export const BELIEF_BARE_SLUGS = Object.keys(_beliefsData).sort();

// Namespaced belief slugs (with `belief.` prefix). The form classifier emits
// and groqHandler partitions on.
export const BELIEF_SLUGS = BELIEF_BARE_SLUGS.map((s) => `${BELIEF_NAMESPACE}${s}`);

export const BELIEF_SLUGS_SET = new Set(BELIEF_SLUGS);
export const BELIEF_BARE_SLUGS_SET = new Set(BELIEF_BARE_SLUGS);

// True if `slug` is a namespaced belief slug (starts with `belief.` and the
// bare portion is in BELIEF_BARE_SLUGS_SET).
export function isBeliefSlug(slug) {
  if (typeof slug !== 'string' || !slug.startsWith(BELIEF_NAMESPACE)) return false;
  const bare = slug.slice(BELIEF_NAMESPACE.length);
  return BELIEF_BARE_SLUGS_SET.has(bare);
}

// Strip namespace from a belief slug. Returns the bare slug, or null if input
// isn't a known belief slug. Used by retrieval to look up raw belief data.
export function bareBeliefSlug(slug) {
  return isBeliefSlug(slug) ? slug.slice(BELIEF_NAMESPACE.length) : null;
}
