#!/usr/bin/env node
// scripts/sync-chrome.mjs
//
// Rewrites the chrome blocks in each hand-edited v2 page from the canonical
// source in scripts/lib/chrome.mjs. Idempotent: running it twice yields no diff.
//
// Marker convention (HTML comments):
//   <!-- chrome:preload -->  ...  <!-- /chrome:preload -->
//   <!-- chrome:css -->      ...  <!-- /chrome:css -->
//   <!-- chrome:dom -->      ...  <!-- /chrome:dom -->
//   <!-- chrome:script -->   ...  <!-- /chrome:script -->
//
// First-time install: each page MUST have these markers in place, wrapping the
// existing chrome content (or empty content if migrating fresh). The script
// rewrites only what's between the markers — page-specific content stays untouched.
//
// Usage:
//   node scripts/sync-chrome.mjs           # sync, write changes
//   node scripts/sync-chrome.mjs --check   # exit 1 if any page would change (CI guard)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  SHARED_PRELOAD_HTML,
  SHARED_CHROME_CSS,
  SVG_SPRITE,
  SHARED_HEADER_HTML,
  SHARED_AAMARK_HTML,
  AAMARK_SCRIPT,
} from './lib/chrome.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');

// Hand-edited v2 pages. Wiki pages are regenerated by build-wiki.mjs and pull
// chrome from the same module — so they don't need sync.
const PAGES = [
  'index.html',
  '404.html',
  'enter/index.html',
  'resume/index.html',
  'lab/index.html',
  'lab/ai-resume/index.html',
  'lab/product-shape/index.html',
  'lab/second-brain/index.html',
  'lab/voice-ai-production/index.html',
  'wiki/index.html',
];

// Block specs: [marker name, canonical content, opening indent for the content].
// The script preserves the indentation of the opening marker line and applies it
// to each line of the canonical content.
const BLOCKS = [
  { name: 'preload', body: SHARED_PRELOAD_HTML },
  { name: 'css',     body: SHARED_CHROME_CSS },
  // dom = combined sprite + header + aa-mark when they're contiguous (most pages).
  { name: 'dom',     body: `${SVG_SPRITE}\n\n${SHARED_HEADER_HTML}\n\n${SHARED_AAMARK_HTML}` },
  // Granular variants — for pages where chrome elements aren't contiguous in
  // DOM (e.g. /enter has a keyboard backdrop between header and aa-mark).
  // Use these instead of chrome:dom when needed.
  { name: 'sprite',  body: SVG_SPRITE },
  { name: 'header',  body: SHARED_HEADER_HTML },
  { name: 'aamark',  body: SHARED_AAMARK_HTML },
  { name: 'script',  body: `<script>${AAMARK_SCRIPT}</script>` },
];

const CHECK_MODE = process.argv.includes('--check');

function syncFile(absPath) {
  const original = fs.readFileSync(absPath, 'utf8');
  let updated = original;
  const missingMarkers = [];

  for (const block of BLOCKS) {
    const open = `<!-- chrome:${block.name} -->`;
    const close = `<!-- /chrome:${block.name} -->`;
    const idx = updated.indexOf(open);
    if (idx === -1) {
      missingMarkers.push(block.name);
      continue;
    }
    const closeIdx = updated.indexOf(close, idx);
    if (closeIdx === -1) {
      throw new Error(`${absPath}: opening marker ${open} found but no closing ${close}`);
    }

    // Body content is emitted verbatim. Markers should be placed at the same
    // column as the canonical block expects (chrome.mjs CSS body starts with
    // 2-space indent so place chrome:css markers at 2-space indent inside
    // <style>; chrome:dom/script bodies are unindented so place those markers
    // at column 0).
    const lineStart = updated.lastIndexOf('\n', idx) + 1;
    const indent = updated.slice(lineStart, idx).match(/^\s*/)[0];

    const before = updated.slice(0, idx + open.length);
    const after = updated.slice(closeIdx);
    updated = `${before}\n${block.body}\n${indent}${after}`;
  }

  return { original, updated, missingMarkers };
}

let changed = 0;
let skipped = 0;
const issues = [];

for (const rel of PAGES) {
  const abs = path.join(repoRoot, rel);
  if (!fs.existsSync(abs)) {
    issues.push(`MISSING: ${rel}`);
    continue;
  }
  let result;
  try {
    result = syncFile(abs);
  } catch (e) {
    issues.push(`${rel}: ${e.message}`);
    continue;
  }
  if (result.missingMarkers.length === BLOCKS.length) {
    // Page has no markers at all — first install pending. Skip with a notice.
    issues.push(`${rel}: no chrome markers found (skipped — add markers to enable sync)`);
    skipped++;
    continue;
  }
  if (result.missingMarkers.length > 0) {
    issues.push(`${rel}: missing markers [${result.missingMarkers.join(', ')}]`);
  }
  if (result.updated !== result.original) {
    if (CHECK_MODE) {
      issues.push(`${rel}: would change (run sync to apply)`);
    } else {
      fs.writeFileSync(abs, result.updated);
      console.log(`[sync-chrome] updated ${rel}`);
    }
    changed++;
  } else {
    console.log(`[sync-chrome] in sync   ${rel}`);
  }
}

if (issues.length) {
  console.error('\n[sync-chrome] issues:');
  for (const i of issues) console.error(`  - ${i}`);
}

if (CHECK_MODE && (changed > 0 || issues.some((i) => i.includes('would change')))) {
  console.error(`\n[sync-chrome] CHECK FAILED: ${changed} page(s) out of sync`);
  process.exit(1);
}

console.log(`\n[sync-chrome] done. ${changed} updated, ${skipped} skipped, ${PAGES.length - skipped} pages with markers.`);
